actions:
- commands:
  - /bin/sh
  - -c
  - cuking --input_uri=${INPUT_URI} --output_uri=${OUTPUT_URI} --requester_pays_project=cpg-gnomad-production-27bb --king_coeff_threshold=${KING_COEFF_THRESHOLD}
  imageUri: us-central1-docker.pkg.dev/cpg-gnomad-production-27bb/images/cuking:latest
- alwaysRun: true
  commands:
  - /bin/sh
  - -c
  - gsutil -u cpg-gnomad-production-27bb -m -q cp /google/logs/output ${LOGGING_OUTPUT}
  imageUri: google/cloud-sdk:slim
timeout: 72000s
