name: Build Docker image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
      DOCKER_IMAGE: australia-southeast1-docker.pkg.dev/cpg-common/images/cuking:${{ github.sha }}

    steps:
      - uses: actions/checkout@v3

      - name: gcloud setup
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: cpg-common
          service_account_key: ${{ secrets.GCP_DEPLOY_KEY }}

      - name: gcloud docker auth
        run: gcloud auth configure-docker australia-southeast1-docker.pkg.dev
      
      - name: build image
        run: docker build --tag=$DOCKER_IMAGE .

      - name: push image
        run: docker push $DOCKER_IMAGE
