name: Build and push Docker image

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1

    steps:
      - name: gcloud setup
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: cpg-common
          service_account_key: ${{ secrets.GCP_DEPLOY_KEY }}

      - name: gcloud docker auth
        run: gcloud auth configure-docker australia-southeast1-docker.pkg.dev
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: australia-southeast1-docker.pkg.dev/cpg-common/images/cuking:${{ github.sha }}